### ISSUE TITLE
kismet-kml do not work with updated kismet

### ISSUE THREAD

**Issue by samWieczorek** [jnsgruk/kismet-kml#1]
It seems that  kismet db format has been changed because the script does not work anymore.
Here is the error message:

```
Traceback (most recent call last):
  File "kismet-kml.py", line 329, in <module>
    kmlGen = KMLGen(args.filename, args.print, args.inplace)
  File "kismet-kml.py", line 31, in __init__
    self.parseData()
  File "kismet-kml.py", line 71, in parseData
    self.clients = list(map(lambda x: self.parseClient(x), clients))
  File "kismet-kml.py", line 71, in <lambda>
    self.clients = list(map(lambda x: self.parseClient(x), clients))
  File "kismet-kml.py", line 181, in parseClient
    fields.update(self.getProbes(device_json))
  File "kismet-kml.py", line 134, in getProbes
    row_probes = device_json["dot11.device"]["dot11.device.responded_ssid_map"]
KeyError: 'dot11.device.responded_ssid_map'
```

After a deeper look into your code and some kismet files, it appears that some other keys are not available in the kismet format anymore

**Comment by jnsgruk** [comment]
Hey Sam, thanks for the feedback. 

I will try and take a look at this over the next few days if I get a chance. 

I've not used this for some months so not surprised. Looks like a reasonably easy fix, just need to look up some details of the new format.

**Comment by samWieczorek** [comment]
Yes, i think it is not quite complicated. However, my skills in Python are not yet very good and I preferred ask you

Best  

Sam
________________________________________
De : Jon Seager [notifications@github.com]
Envoyé : lundi 14 décembre 2020 12:02
À : jnsgruk/kismet-kml
Cc : WIECZOREK Samuel 175264; Author
Objet : Re: [jnsgruk/kismet-kml] kismet-kml do not work with updated kismet (#1)

Hey Sam, thanks for the feedback.

I will try and take a look at this over the next few days if I get a chance.

I've not used this for some months so not surprised. Looks like a reasonably easy fix, just need to look up some details of the new format.

**Comment by jnsgruk** [comment]
If you are able to provide a sample Kismet file, that would be really useful, but I appreciate you may not wish to share that information

**Comment by samWieczorek** [comment]
Here it is ! :)
________________________________________
De : Jon Seager [notifications@github.com]
Envoyé : lundi 14 décembre 2020 12:13
À : jnsgruk/kismet-kml
Cc : WIECZOREK Samuel 175264; Author
Objet : Re: [jnsgruk/kismet-kml] kismet-kml do not work with updated kismet (#1)

If you are able to provide a sample Kismet file, that would be really useful, but I appreciate you may not wish to share that information

**Comment by jnsgruk** [comment]
Hi Sam, should be fixed with [this commit](https://github.com/jnsgruk/kismet-kml/commit/dfb6c0f27d0afbb1b0ce594d66f7be0ecb337587) and [this commit](https://github.com/jnsgruk/kismet-kml/commit/c9153707914a8d0568d27d550d3d7f126246c985).

Note that parsing of these files is relatively naive - any devices without locations will simply not be included in the KML file. You'll note however, that the tool also outputs a JSON file, which contains all devices and a little more detail. It can be visualised with my other project, [monza](https://github.com/jnsgruk/monza). Let me know if that project is of use, like this one it has been a while since I updated it.

**Comment by samWieczorek** [comment]
Hi Jon,

Ok thanks ! I will take a look at your two repositories.

Sam
________________________________________
De : Jon Seager [notifications@github.com]
Envoyé : mardi 15 décembre 2020 11:14
À : jnsgruk/kismet-kml
Cc : WIECZOREK Samuel 175264; Author
Objet : Re: [jnsgruk/kismet-kml] kismet-kml do not work with updated kismet (#1)

Hi Sam, should be fixed with this commit<https://github.com/jnsgruk/kismet-kml/commit/dfb6c0f27d0afbb1b0ce594d66f7be0ecb337587> and this commit<https://github.com/jnsgruk/kismet-kml/commit/c9153707914a8d0568d27d550d3d7f126246c985>.

Note that parsing of these files is relatively naive - any devices without locations will simply not be included in the KML file. You'll note however, that the tool also outputs a JSON file, which contains all devices and a little more detail. It can be visualised with my other project, monza<https://github.com/jnsgruk/monza>. Let me know if that project is of use, like this one it has been a while since I updated it.
